name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v3.3.1
    - name: Build with Gradle Wrapper
      run: ./gradlew generatejavascript
    - name: make offline download
      run: bash MakeOfflineDownload.sh
    - name: upload offline download
      uses: actions/upload-artifact@v4
      with:
        path: javascript/Shadow_Client_Offline.html
