name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup jdk 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: generate javascript
      run: ./gradlew generatejavascript
    - name: make offline download
      run: bash MakeOfflineDownload.sh
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: javascript/Shadow_Client_Offline.html
