name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/setup-gradle@v3
      with:
        cache-disabled: true
        validate-wrappers: true
    - run: chmod +x ./gradlew
    - run: ./gradlew build
    - run: ./gradlew generateJavascript
    - run: bash MakeOfflineDownload.sh
    - uses: actions/upload-artifact@v4
      with:
        path: javascript/Shadow_Client.html
