name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    - name: compile javascript
      run: bash CompileJS.sh
    - name: build with gradle wrapper
      run: ./gradlew build
    - name: zip javascript folder
      run: zip -r javascript.zip javascript/*
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          javascript/web_files.zip
          javascript/Shadow_Client_Offline.html
