name: deploy to pages
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@main
    - name: setup java
      uses: actions/setup-java@main
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@main
    - name: compile javascript
      run: chmod +x ./gradlew; ./gradlew generateJavascript
    - name: compile assets
      run: bash CompileEPK.sh
    - name: upload-pages-artifact is very bad
      run: mkdir javascript/web; cp -r javascript/lang javascript/index.html javascript/classes.js javascript/classes.js.map javascript/assets.epk javascript/web
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@main
      with:
        name: github-pages
        path: javascript/lang javascript/index.html javascript/classes.js javascript/classes.js.map javascript/assets.epk

  deploy:
    needs: build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@main
      - name: delete artifact
        uses: geekyeggo/delete-artifact@main
        with:
          name: github-pages
