name: deploy to pages
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: compile javascript
      run: bash CompileJS.sh
    - name: compile assets
      run: bash CompileEPK.sh
    - name: upload-pages-artifact is very bad
      run: mkdir javascript/web; cp -r javascript/lang javascript/index.html javascript/classes.js javascript/classes.js.map javascript/assets.epk javascript/web; echo 'javascript/js'; ls javascript/js
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: javascript/web

  deploy:
    needs: build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
      - name: delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
