name: deploy to pages
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: compile javascript
      run: bash CompileJS.sh
    - name: compile assets
      run: bash CompileEPK.sh
    - name: upload-pages-artifact is very bad
      run: mkdir _site/; cp --recursive javascript/lang/ javascript/index.html javascript/classes.js javascript/classes.js.map javascript/assets.epk _site/
    - name: upload pages artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
